services:
  docs:
    image: blimp_local_docs
    container_name: blimp_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./blimp:/app/blimp:z
    ports:
      - '9000:9000'
    command: /start-docs
